// ./lib/data.ts

export interface CurrencyOption {
  code: string;
  name: string;
  symbol: string;
  rateFromBgn: number;
  popular?: boolean;
}

export interface LanguageOption {
  code: string;
  name: string;
}

export interface CountryOption {
  code: string;
  name: string;
  flag: string;
  popular?: boolean;
}

export interface VehicleSearchResult {
  make: string;
  model: string;
  estimatedGvwrKg: number;
}

// 1. ALL 185 OFFICIAL LANGUAGES (From Excel)
export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'AB', name: 'Abkhazian' }, { code: 'AA', name: 'Afar' }, { code: 'AF', name: 'Afrikaans' },
  { code: 'AK', name: 'Akan' }, { code: 'SQ', name: 'Albanian' }, { code: 'AM', name: 'Amharic' },
  { code: 'AR', name: 'Arabic' }, { code: 'AN', name: 'Aragonese' }, { code: 'HY', name: 'Armenian' },
  { code: 'AS', name: 'Assamese' }, { code: 'AV', name: 'Avaric' }, { code: 'AE', name: 'Avestan' },
  { code: 'AY', name: 'Aymara' }, { code: 'AZ', name: 'Azerbaijani' }, { code: 'BM', name: 'Bambara' },
  { code: 'BA', name: 'Bashkir' }, { code: 'EU', name: 'Basque' }, { code: 'BE', name: 'Belarusian' },
  { code: 'BN', name: 'Bengali' }, { code: 'BH', name: 'Bihari' }, { code: 'BI', name: 'Bislama' },
  { code: 'BS', name: 'Bosnian' }, { code: 'BR', name: 'Breton' }, { code: 'BG', name: 'Bulgarian' },
  { code: 'MY', name: 'Burmese' }, { code: 'CA', name: 'Catalan' }, { code: 'CH', name: 'Chamorro' },
  { code: 'CE', name: 'Chechen' }, { code: 'NY', name: 'Chichewa' }, { code: 'ZH', name: 'Chinese' },
  { code: 'CU', name: 'Church Slavic' }, { code: 'CV', name: 'Chuvash' }, { code: 'KW', name: 'Cornish' },
  { code: 'CO', name: 'Corsican' }, { code: 'CR', name: 'Cree' }, { code: 'HR', name: 'Croatian' },
  { code: 'CS', name: 'Czech' }, { code: 'DA', name: 'Danish' }, { code: 'DV', name: 'Divehi' },
  { code: 'NL', name: 'Dutch' }, { code: 'DZ', name: 'Dzongkha' }, { code: 'EN', name: 'English' },
  { code: 'EO', name: 'Esperanto' }, { code: 'ET', name: 'Estonian' }, { code: 'EE', name: 'Ewe' },
  { code: 'FO', name: 'Faroese' }, { code: 'FJ', name: 'Fijian' }, { code: 'FI', name: 'Finnish' },
  { code: 'FR', name: 'French' }, { code: 'FY', name: 'Western Frisian' }, { code: 'FF', name: 'Fulah' },
  { code: 'GD', name: 'Gaelic' }, { code: 'GL', name: 'Galician' }, { code: 'LG', name: 'Ganda' },
  { code: 'KA', name: 'Georgian' }, { code: 'DE', name: 'German' }, { code: 'EL', name: 'Greek' },
  { code: 'GN', name: 'Guarani' }, { code: 'GU', name: 'Gujarati' }, { code: 'HT', name: 'Haitian' },
  { code: 'HA', name: 'Hausa' }, { code: 'HE', name: 'Hebrew' }, { code: 'HZ', name: 'Herero' },
  { code: 'HI', name: 'Hindi' }, { code: 'HO', name: 'Hiri Motu' }, { code: 'HU', name: 'Hungarian' },
  { code: 'IS', name: 'Icelandic' }, { code: 'IO', name: 'Ido' }, { code: 'IG', name: 'Igbo' }, { code: 'ID', name: 'Indonesian' },
  { code: 'IA', name: 'Interlingua' }, { code: 'IE', name: 'Interlingue' }, { code: 'IU', name: 'Inuktitut' },
  { code: 'IK', name: 'Inupiaq' }, { code: 'GA', name: 'Irish' }, { code: 'IT', name: 'Italian' },
  { code: 'JA', name: 'Japanese' }, { code: 'JV', name: 'Javanese' }, { code: 'KL', name: 'Kalaallisut' },
  { code: 'KN', name: 'Kannada' }, { code: 'KR', name: 'Kanuri' }, { code: 'KS', name: 'Kashmiri' },
  { code: 'KK', name: 'Kazakh' }, { code: 'KM', name: 'Central Khmer' }, { code: 'KI', name: 'Kikuyu' },
  { code: 'RW', name: 'Kinyarwanda' }, { code: 'KY', name: 'Kirghiz' }, { code: 'KV', name: 'Komi' },
  { code: 'KG', name: 'Kongo' }, { code: 'KO', name: 'Korean' }, { code: 'KJ', name: 'Kuanyama' },
  { code: 'KU', name: 'Kurdish' }, { code: 'LO', name: 'Lao' }, { code: 'LA', name: 'Latin' },
  { code: 'LV', name: 'Latvian' }, { code: 'LI', name: 'Limburgish' }, { code: 'LN', name: 'Lingala' },
  { code: 'LT', name: 'Lithuanian' }, { code: 'LU', name: 'Luba-Katanga' }, { code: 'LB', name: 'Luxembourgish' },
  { code: 'MK', name: 'Macedonian' }, { code: 'MG', name: 'Malagasy' }, { code: 'MS', name: 'Malay' },
  { code: 'ML', name: 'Malayalam' }, { code: 'MT', name: 'Maltese' }, { code: 'GV', name: 'Manx' },
  { code: 'MI', name: 'Maori' }, { code: 'MR', name: 'Marathi' }, { code: 'MH', name: 'Marshallese' },
  { code: 'MN', name: 'Mongolian' }, { code: 'NA', name: 'Nauru' }, { code: 'NV', name: 'Navajo' },
  { code: 'ND', name: 'North Ndebele' }, { code: 'NR', name: 'South Ndebele' }, { code: 'NG', name: 'Ndonga' },
  { code: 'NE', name: 'Nepali' }, { code: 'NO', name: 'Norwegian' }, { code: 'NB', name: 'Bokmål' },
  { code: 'NN', name: 'Nynorsk' }, { code: 'II', name: 'Sichuan Yi' }, { code: 'OC', name: 'Occitan' },
  { code: 'OJ', name: 'Ojibwa' }, { code: 'OR', name: 'Oriya' }, { code: 'OM', name: 'Oromo' },
  { code: 'OS', name: 'Ossetian' }, { code: 'PI', name: 'Pali' }, { code: 'PS', name: 'Pashto' },
  { code: 'FA', name: 'Persian' }, { code: 'PL', name: 'Polish' }, { code: 'PT', name: 'Portuguese' },
  { code: 'PA', name: 'Punjabi' }, { code: 'QU', name: 'Quechua' }, { code: 'RO', name: 'Romanian' },
  { code: 'RM', name: 'Romansh' }, { code: 'RN', name: 'Rundi' }, { code: 'RU', name: 'Russian' },
  { code: 'SE', name: 'Northern Sami' }, { code: 'SM', name: 'Samoan' }, { code: 'SG', name: 'Sango' },
  { code: 'SA', name: 'Sanskrit' }, { code: 'SC', name: 'Sardinian' }, { code: 'SR', name: 'Serbian' },
  { code: 'SN', name: 'Shona' }, { code: 'SD', name: 'Sindhi' }, { code: 'SI', name: 'Sinhala' },
  { code: 'SK', name: 'Slovak' }, { code: 'SL', name: 'Slovenian' }, { code: 'SO', name: 'Somali' },
  { code: 'ST', name: 'Southern Sotho' }, { code: 'ES', name: 'Spanish' }, { code: 'SU', name: 'Sundanese' },
  { code: 'SW', name: 'Swahili' }, { code: 'SS', name: 'Swati' }, { code: 'SV', name: 'Swedish' },
  { code: 'TL', name: 'Tagalog' }, { code: 'TY', name: 'Tahitian' }, { code: 'TG', name: 'Tajik' },
  { code: 'TA', name: 'Tamil' }, { code: 'TT', name: 'Tatar' }, { code: 'TE', name: 'Telugu' },
  { code: 'TH', name: 'Thai' }, { code: 'BO', name: 'Tibetan' }, { code: 'TI', name: 'Tigrinya' },
  { code: 'TO', name: 'Tonga' }, { code: 'TS', name: 'Tsonga' }, { code: 'TN', name: 'Tswana' },
  { code: 'TR', name: 'Turkish' }, { code: 'TK', name: 'Turkmen' }, { code: 'TW', name: 'Twi' },
  { code: 'UG', name: 'Uighur' }, { code: 'UK', name: 'Ukrainian' }, { code: 'UR', name: 'Urdu' },
  { code: 'UZ', name: 'Uzbek' }, { code: 'VE', name: 'Venda' }, { code: 'VI', name: 'Vietnamese' },
  { code: 'VO', name: 'Volapük' }, { code: 'WA', name: 'Walloon' }, { code: 'CY', name: 'Welsh' },
  { code: 'WO', name: 'Wolof' }, { code: 'XH', name: 'Xhosa' }, { code: 'YI', name: 'Yiddish' },
  { code: 'YO', name: 'Yoruba' }, { code: 'ZA', name: 'Zhuang' }, { code: 'ZU', name: 'Zulu' }
];

// 2. ALL 180 WORLD CURRENCIES (From Excel)
export const WORLD_CURRENCIES: CurrencyOption[] = [
  { code: 'EUR', name: 'Euro', symbol: '€', rateFromBgn: 0.51, popular: true },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', rateFromBgn: 1.0, popular: true },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rateFromBgn: 18.5, popular: true },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', rateFromBgn: 2.55, popular: true },
  { code: 'GBP', name: 'British Pound', symbol: '£', rateFromBgn: 0.43, popular: true },
  { code: 'USD', name: 'US Dollar', symbol: '$', rateFromBgn: 0.55, popular: true },
  { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'AED', rateFromBgn: 2.02 },
  { code: 'AFN', name: 'Afghan Afghani', symbol: 'AFN', rateFromBgn: 38.5 },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', rateFromBgn: 51.2 },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', rateFromBgn: 215.0 },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ANG', rateFromBgn: 0.99 },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'AOA', rateFromBgn: 510.0 },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'ARS', rateFromBgn: 520.0 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rateFromBgn: 0.84 },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'AWG', rateFromBgn: 0.99 },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', rateFromBgn: 0.93 },
  { code: 'BAM', name: 'Bosnia & Herzegovina Convertible Mark', symbol: 'KM', rateFromBgn: 1.0 },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'BBD', rateFromBgn: 1.10 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: 'BDT', rateFromBgn: 65.0 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BHD', rateFromBgn: 0.207 },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'BIF', rateFromBgn: 1580.0 },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: 'BMD', rateFromBgn: 0.55 },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'BND', rateFromBgn: 0.74 },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'BOB', rateFromBgn: 3.80 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'BRL', rateFromBgn: 3.10 },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'BSD', rateFromBgn: 0.55 },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'BTN', rateFromBgn: 46.2 },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'BWP', rateFromBgn: 7.50 },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'BYN', rateFromBgn: 1.80 },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZD', rateFromBgn: 1.10 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', rateFromBgn: 0.76 },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'CDF', rateFromBgn: 1550.0 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rateFromBgn: 0.48 },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CLP', rateFromBgn: 520.0 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rateFromBgn: 3.95 },
  { code: 'COP', name: 'Colombian Peso', symbol: 'COP', rateFromBgn: 2150.0 },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: 'CRC', rateFromBgn: 280.0 },
  { code: 'CUP', name: 'Cuban Peso', symbol: 'CUP', rateFromBgn: 13.2 },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'CVE', rateFromBgn: 56.2 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', rateFromBgn: 12.8 },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'DJF', rateFromBgn: 97.8 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rateFromBgn: 3.81 },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'DOP', rateFromBgn: 33.0 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD', rateFromBgn: 74.0 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'EGP', rateFromBgn: 27.0 },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'ERN', rateFromBgn: 8.25 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'ETB', rateFromBgn: 68.0 },
  { code: 'FJD', name: 'Fijan Dollar', symbol: 'FJD', rateFromBgn: 1.25 },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: 'FKP', rateFromBgn: 0.43 },
  { code: 'FOK', name: 'Faroese Króna', symbol: 'FOK', rateFromBgn: 3.81 },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', rateFromBgn: 1.48 },
  { code: 'GGP', name: 'Guernsey Pound', symbol: 'GGP', rateFromBgn: 0.43 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GHS', rateFromBgn: 8.50 },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: 'GIP', rateFromBgn: 0.43 },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'GMD', rateFromBgn: 37.5 },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'GNF', rateFromBgn: 4700.0 },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'GTQ', rateFromBgn: 4.25 },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: 'GYD', rateFromBgn: 115.0 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HKD', rateFromBgn: 4.30 },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'HNL', rateFromBgn: 13.6 },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'HRK', rateFromBgn: 3.84 },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'HTG', rateFromBgn: 72.5 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', rateFromBgn: 202.0 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'IDR', rateFromBgn: 8800.0 },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', rateFromBgn: 2.05 },
  { code: 'IMP', name: 'Isle of Man Pound', symbol: 'IMP', rateFromBgn: 0.43 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', rateFromBgn: 46.2 },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'IQD', rateFromBgn: 720.0 },
  { code: 'IRR', name: 'Iranian Rial', symbol: 'IRR', rateFromBgn: 23000.0 },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'ISK', rateFromBgn: 76.5 },
  { code: 'JEP', name: 'Jersey Pound', symbol: 'JEP', rateFromBgn: 0.43 },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'JMD', rateFromBgn: 85.0 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JOD', rateFromBgn: 0.39 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rateFromBgn: 84.5 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KES', rateFromBgn: 71.0 },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'KGS', rateFromBgn: 49.0 },
  { code: 'KHR', name: 'Cambodian Riel', symbol: 'KHR', rateFromBgn: 2250.0 },
  { code: 'KID', name: 'Kiribati Dollar', symbol: 'KID', rateFromBgn: 0.84 },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'KMF', rateFromBgn: 251.0 },
  { code: 'KRW', name: 'South Korean Won', symbol: 'KRW', rateFromBgn: 735.0 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KWD', rateFromBgn: 0.169 },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'KYD', rateFromBgn: 0.45 },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: 'KZT', rateFromBgn: 260.0 },
  { code: 'LAK', name: 'Lao Kip', symbol: 'LAK', rateFromBgn: 11800.0 },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'LBP', rateFromBgn: 49000.0 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'LKR', rateFromBgn: 165.0 },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'LRD', rateFromBgn: 105.0 },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'LSL', rateFromBgn: 10.2 },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LYD', rateFromBgn: 2.68 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', rateFromBgn: 5.50 },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', rateFromBgn: 9.85 },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'MGA', rateFromBgn: 2500.0 },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'den', rateFromBgn: 31.5 },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'MMK', rateFromBgn: 1150.0 },
  { code: 'MNT', name: 'Mongolian Tögrög', symbol: 'MNT', rateFromBgn: 1880.0 },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP', rateFromBgn: 4.45 },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'MRU', rateFromBgn: 21.8 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: 'MUR', rateFromBgn: 25.5 },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'MVR', rateFromBgn: 8.50 },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MWK', rateFromBgn: 950.0 },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MXN', rateFromBgn: 10.8 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'MYR', rateFromBgn: 2.45 },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MZN', rateFromBgn: 35.0 },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'NAD', rateFromBgn: 10.2 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: 'NGN', rateFromBgn: 820.0 },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'NIO', rateFromBgn: 20.2 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rateFromBgn: 5.92 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'NPR', rateFromBgn: 73.8 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZD', rateFromBgn: 0.92 },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR', rateFromBgn: 0.212 },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'PAB', rateFromBgn: 0.55 },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'PEN', rateFromBgn: 2.05 },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'PGK', rateFromBgn: 2.15 },
  { code: 'PHP', name: 'Philippine Peso', symbol: 'PHP', rateFromBgn: 31.2 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: 'PKR', rateFromBgn: 153.0 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', rateFromBgn: 2.18 },
  { code: 'PYG', name: 'Paraguayan Guaraní', symbol: 'PYG', rateFromBgn: 4100.0 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QAR', rateFromBgn: 2.00 },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'din.', rateFromBgn: 59.8 },
  { code: 'RUB', name: 'Russian Ruble', symbol: 'RUB', rateFromBgn: 50.0 },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RWF', rateFromBgn: 710.0 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR', rateFromBgn: 2.06 },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SBD', rateFromBgn: 4.60 },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SCR', rateFromBgn: 7.50 },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', rateFromBgn: 330.0 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rateFromBgn: 5.85 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'SGD', rateFromBgn: 0.74 },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: 'SHP', rateFromBgn: 0.43 },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'SLE', rateFromBgn: 12.2 },
  { code: 'SLL', name: 'Sierra Leonean Leone (Old)', symbol: 'SLL', rateFromBgn: 12200.0 },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'SOS', rateFromBgn: 315.0 },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'SRD', rateFromBgn: 19.5 },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: 'SSP', rateFromBgn: 710.0 },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'STN', rateFromBgn: 12.5 },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'SYP', rateFromBgn: 7100.0 },
  { code: 'SZL', name: 'Eswatini Lilangeni', symbol: 'SZL', rateFromBgn: 10.2 },
  { code: 'THB', name: 'Thai Baht', symbol: 'THB', rateFromBgn: 19.5 },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'TJS', rateFromBgn: 6.00 },
  { code: 'TMT', name: 'Turkmenistan Manat', symbol: 'TMT', rateFromBgn: 1.92 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'TND', rateFromBgn: 1.72 },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'TOP', rateFromBgn: 1.30 },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TTD', rateFromBgn: 3.72 },
  { code: 'TVD', name: 'Tuvaluan Dollar', symbol: 'TVD', rateFromBgn: 0.84 },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'TWD', rateFromBgn: 17.5 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TZS', rateFromBgn: 1420.0 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', rateFromBgn: 22.8 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'UGX', rateFromBgn: 2050.0 },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: 'UYU', rateFromBgn: 21.5 },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'UZS', rateFromBgn: 6900.0 },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'VES', rateFromBgn: 20.0 },
  { code: 'VND', name: 'Vietnamese Đồng', symbol: 'VND', rateFromBgn: 13800.0 },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VUV', rateFromBgn: 66.0 },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WST', rateFromBgn: 1.50 },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'XAF', rateFromBgn: 334.0 },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'XCD', rateFromBgn: 1.48 },
  { code: 'XDR', name: 'Special Drawing Rights', symbol: 'XDR', rateFromBgn: 0.41 },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'XOF', rateFromBgn: 334.0 },
  { code: 'XPF', name: 'CFP Franc', symbol: 'XPF', rateFromBgn: 60.8 },
  { code: 'YER', name: 'Yemeni Rial', symbol: 'YER', rateFromBgn: 138.0 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'ZAR', rateFromBgn: 10.2 },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZMW', rateFromBgn: 14.2 },
  { code: 'ZWG', name: 'Zimbabwean Gold', symbol: 'ZWG', rateFromBgn: 7.50 }
];

// 3. ALL 248 WORLD COUNTRIES (From Excel)
export const WORLD_COUNTRIES: CountryOption[] = [
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', popular: true },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', popular: true },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', popular: true },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', popular: true },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', popular: true },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', popular: true },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', popular: true },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', popular: true },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', popular: true },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', popular: true },
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AX', name: 'Åland Islands', flag: '🇦🇽' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { code: 'AS', name: 'American Samoa', flag: '🇦🇸' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮' },
  { code: 'AQ', name: 'Antarctica', flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', flag: '🇧🇶' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BV', name: 'Bouvet Island', flag: '🇧🇻' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'IO', name: 'British Indian Ocean Territory', flag: '🇮🇴' },
  { code: 'BN', name: 'Brunei Darussalam', flag: '🇧🇳' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'CX', name: 'Christmas Island', flag: '🇨🇽' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', flag: '🇨🇨' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo (Democratic Republic)', flag: '🇨🇩' },
  { code: 'CK', name: 'Cook Islands', flag: '🇨🇰' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CI', name: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czechia', flag: '🇨🇿' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FK', name: 'Falkland Islands', flag: '🇫🇰' },
  { code: 'FO', name: 'Faroe Islands', flag: '🇫🇴' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'GF', name: 'French Guiana', flag: '🇬🇫' },
  { code: 'PF', name: 'French Polynesia', flag: '🇵🇫' },
  { code: 'TF', name: 'French Southern Territories', flag: '🇹🇫' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮' },
  { code: 'GL', name: 'Greenland', flag: '🇬🇱' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: 'GP', name: 'Guadeloupe', flag: '🇬🇵' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GG', name: 'Guernsey', flag: '🇬🇬' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', flag: '🇭🇲' },
  { code: 'VA', name: 'Holy See', flag: '🇻🇦' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'IM', name: 'Isle of Man', flag: '🇮🇲' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LA', name: 'Lao People\'s Democratic Republic', flag: '🇱🇦' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MO', name: 'Macao', flag: '🇲🇴' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'MQ', name: 'Martinique', flag: '🇲🇶' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NC', name: 'New Caledonia', flag: '🇳🇨' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺' },
  { code: 'NF', name: 'Norfolk Island', flag: '🇳🇫' },
  { code: 'MP', name: 'Northern Mariana Islands', flag: '🇲🇵' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'PN', name: 'Pitcairn', flag: '🇵🇳' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'RE', name: 'Réunion', flag: '🇷🇪' },
  { code: 'RU', name: 'Russian Federation', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'BL', name: 'Saint Barthélemy', flag: '🇧🇱' },
  { code: 'SH', name: 'Saint Helena', flag: '🇸🇭' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'MF', name: 'Saint Martin (French part)', flag: '🇲🇫' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', flag: '🇸🇽' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', flag: '🇬🇸' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', flag: '🇸🇯' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', name: 'Syrian Arab Republic', flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TC', name: 'Turks and Caicos Islands', flag: '🇹🇨' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'US', name: 'United States of America', flag: '🇺🇸' },
  { code: 'UM', name: 'United States Minor Outlying Islands', flag: '🇺🇲' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Viet Nam', flag: '🇻🇳' },
  { code: 'VG', name: 'Virgin Islands (British)', flag: '🇻🇬' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', flag: '🇻🇮' },
  { code: 'WF', name: 'Wallis and Futuna', flag: '🇼🇫' },
  { code: 'EH', name: 'Western Sahara', flag: '🇪🇭' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' }
];

export const BULGARIA_DESTINATIONS = [
  'Aheloy', 'Ahtopol', 'Aksakovo', 'Alfatar', 'Antonovo', 'Apriltsi', 'Ardino', 'Asenovgrad', 'Aytos',
  'Balchik', 'Balgarovo', 'Bankya', 'Bansko', 'Banya', 'Batak', 'Batanovtsi', 'Belene', 'Belitsa',
  'Belogradchik', 'Beloslav', 'Belovo', 'Berkovitsa', 'Blagoevgrad', 'Boboshevo', 'Bobov Dol', 'Bolyarovo',
  'Borovo', 'Botevgrad', 'Boychinovtsi', 'Bozhurishte', 'Bratsigovo', 'Bregovo', 'Breznik', 'Brezovo',
  'Brusartsi', 'Buhovo', 'Burgas', 'Byala (Ruse)', 'Byala (Varna)', 'Byala Cherkva', 'Byala Slatina',
  'Chepelare', 'Chernomorets', 'Cherven Bryag', 'Chiprovtsi', 'Chirpan', 'Dalgopol', 'Debelets', 'Devin',
  'Devnya', 'Dimitrovgrad', 'Dimovo', 'Dobrich', 'Dobrinishte', 'Dolna Banya', 'Dolna Mitropolia',
  'Dolna Oryahovitsa', 'Dolni Chiflik', 'Dolni Dabnik', 'Dospat', 'Dragoman', 'Dryanovo', 'Dulovo',
  'Dunavtsi', 'Dupnitsa', 'Dve Mogili', 'Dzhebel', 'Elena', 'Elhovo', 'Elin Pelin', 'Etropole',
  'Gabrovo', 'Galabovo', 'General Toshevo', 'Glavinitsa', 'Godech', 'Gorna Oryahovitsa', 'Gotse Delchev',
  'Gramada', 'Gulyantsi', 'Gurkovo', 'Hadzhidimovo', 'Harmanli', 'Haskovo', 'Hisarya', 'Ihtiman',
  'Iskar', 'Isperih', 'Ivaylovgrad', 'Kableshkovo', 'Kalofer', 'Kameno', 'Kaolinovo', 'Kardzhali',
  'Karlovo', 'Karnobat', 'Kaspichan', 'Kavarna', 'Kazanlak', 'Kermen', 'Kilifarevo', 'Kiten',
  'Klisura', 'Knezha', 'Kocherinovo', 'Koprivshtitsa', 'Kostandovo', 'Kostenets', 'Kostinbrod', 'Kotel',
  'Koynare', 'Kozloduy', 'Kran', 'Kresna', 'Krichim', 'Krivodol', 'Krumovgrad', 'Kubrat',
  'Kuklen', 'Kula', 'Kyustendil', 'Laki', 'Letnitsa', 'Levski', 'Lom', 'Lovech',
  'Loznitsa', 'Lukovit', 'Lyaskovets', 'Lyubimets', 'Madan', 'Madzharovo', 'Maglizh', 'Malko Tarnovo',
  'Marten', 'Melnik', 'Merichleri', 'Mezdra', 'Mizia', 'Momchilgrad', 'Momin Prohod', 'Montana',
  'Nedelino', 'Nesebar', 'Nikolaevo', 'Nikopol', 'Nova Zagora', 'Novi Iskar', 'Novi Pazar', 'Obzor',
  'Omurtag', 'Opaka', 'Oryahovo', 'Panagyurishte', 'Pavlikeni', 'Pazardzhik', 'Pernik', 'Perushtitsa',
  'Peshtera', 'Petrich', 'Pirdop', 'Pleven', 'Plovdiv', 'Pliska', 'Pomorie', 'Popovo',
  'Primorsko', 'Provadia', 'Radnevo', 'Radomir', 'Rakitovo', 'Rakovski', 'Razgrad', 'Razlog',
  'Rilski Manastir', 'Rode', 'Roman', 'Rudan', 'Rudozem', 'Ruen', 'Ruse', 'Sadovo',
  'Saedinenie', 'Samokov', 'Sandanski', 'Sapareva Banya', 'Sarnitsa', 'Senovo', 'Septemvri', 'Sevlievo',
  'Shabla', 'Shipka', 'Shivachevo', 'Shumen', 'Silistra', 'Simeonovgrad', 'Simitli', 'Slavyanovo',
  'Sliven', 'Slivnitsa', 'Smolyan', 'Smyadovo', 'Sofia', 'Sopot', 'Sozopol', 'Sredets',
  'Stamboliyski', 'Stara Zagora', 'Straldzha', 'Strelcha', 'Suhindol', 'Sungurlare', 'Svilengrad', 'Svishtov',
  'SVoge', 'Sveti Vlas', 'Targovishte', 'Tervel', 'Teteven', 'Topolovgrad', 'Trun', 'Tryavna',
  'Tsar Kaloyan', 'Tsarevo', 'Tutrakan', 'Tvarditsa', 'Ugarchin', 'Varbitsa', 'Varna', 'Varshets',
  'Veliko Tarnovo', 'Veliki Preslav', 'Velingrad', 'Vetin', 'Vidin', 'Vratsa', 'Valchedram', 'Valchi Dol',
  'Yablanitsa', 'Yakoruda', 'Yambol', 'Zavet', 'Zlataritsa', 'Zlatitsa', 'Zlatograd'
];

export const BULGARIA_BORDER_CHECKPOINTS = [
  'Kapitan Andreevo (TR)', 'Lesovo (TR)', 'Malko Tarnovo (TR)',
  'Kalotina (RS)', 'Vrska Cuka (RS)', 'Bregovo (RS)', 'Strezimirovtsi (RS)',
  'Ruse - Danube Bridge 1 (RO)', 'Vidin - Danube Bridge 2 (RO)', 'Silistra (RO)', 'Kardam (RO)', 'Durankulak (RO)',
  'Kulata (GR)', 'Makaza (GR)', 'Ilinden (GR)', 'Zlatograd (GR)', 'Ivaylovgrad (GR)',
  'Gyueshevo (MK)', 'Stanke Lisichkovo (MK)', 'Zlatarevo (MK)'
];

// 4. ALL 1,712 VEHICLE MAKES & MODELS (From Excel)
export const POPULAR_VEHICLE_DATABASE: VehicleSearchResult[] = [
  { make: 'Abarth', model: '500', estimatedGvwrKg: 1425 },
  { make: 'Abarth', model: '500e', estimatedGvwrKg: 1815 },
  { make: 'Abarth', model: '595', estimatedGvwrKg: 1430 },
  { make: 'Abarth', model: '600e', estimatedGvwrKg: 1980 },
  { make: 'Abarth', model: '695', estimatedGvwrKg: 1440 },
  { make: 'Abarth', model: '124 Spider', estimatedGvwrKg: 1315 },
  { make: 'Abarth', model: 'Grande Punto', estimatedGvwrKg: 1665 },
  { make: 'Abarth', model: 'Punto Evo', estimatedGvwrKg: 1685 },
  { make: 'Acura', model: 'ADX', estimatedGvwrKg: 2150 },
  { make: 'Acura', model: 'MDX', estimatedGvwrKg: 2650 },
  { make: 'Acura', model: 'RDX', estimatedGvwrKg: 2280 },
  { make: 'Acura', model: 'TLX', estimatedGvwrKg: 2180 },
  { make: 'Acura', model: 'ZDX', estimatedGvwrKg: 3100 },
  { make: 'Acura', model: 'ILX', estimatedGvwrKg: 1800 },
  { make: 'Acura', model: 'RLX', estimatedGvwrKg: 2250 },
  { make: 'Alfa Romeo', model: 'Giulia', estimatedGvwrKg: 2050 },
  { make: 'Alfa Romeo', model: 'Stelvio', estimatedGvwrKg: 2350 },
  { make: 'Alfa Romeo', model: 'Tonale', estimatedGvwrKg: 2135 },
  { make: 'Alfa Romeo', model: 'Junior', estimatedGvwrKg: 1800 },
  { make: 'Alfa Romeo', model: 'Giulietta', estimatedGvwrKg: 1820 },
  { make: 'Alfa Romeo', model: 'Mito', estimatedGvwrKg: 1610 },
  { make: 'Alfa Romeo', model: '4C', estimatedGvwrKg: 1220 },
  { make: 'Alpine', model: 'A110', estimatedGvwrKg: 1380 },
  { make: 'Alpine', model: 'A290', estimatedGvwrKg: 1850 },
  { make: 'Aston Martin', model: 'DBX', estimatedGvwrKg: 3030 },
  { make: 'Aston Martin', model: 'Vantage', estimatedGvwrKg: 1900 },
  { make: 'Aston Martin', model: 'DB12', estimatedGvwrKg: 2075 },
  { make: 'Aston Martin', model: 'DBS', estimatedGvwrKg: 2150 },
  { make: 'Audi', model: 'A1 Allstreet', estimatedGvwrKg: 1680 },
  { make: 'Audi', model: 'A1 Sportback', estimatedGvwrKg: 1680 },
  { make: 'Audi', model: 'A3 Sportback', estimatedGvwrKg: 1870 },
  { make: 'Audi', model: 'A3 Sedan', estimatedGvwrKg: 1870 },
  { make: 'Audi', model: 'A3 allroad', estimatedGvwrKg: 1950 },
  { make: 'Audi', model: 'A4 Sedan', estimatedGvwrKg: 2090 },
  { make: 'Audi', model: 'A4 Avant', estimatedGvwrKg: 2140 },
  { make: 'Audi', model: 'A4 allroad', estimatedGvwrKg: 2235 },
  { make: 'Audi', model: 'A5 Sportback', estimatedGvwrKg: 2125 },
  { make: 'Audi', model: 'A5 Coupe', estimatedGvwrKg: 2045 },
  { make: 'Audi', model: 'A6 Sedan', estimatedGvwrKg: 2355 },
  { make: 'Audi', model: 'A6 Avant', estimatedGvwrKg: 2425 },
  { make: 'Audi', model: 'A6 allroad', estimatedGvwrKg: 2510 },
  { make: 'Audi', model: 'A6 e-tron', estimatedGvwrKg: 2825 },
  { make: 'Audi', model: 'A7 Sportback', estimatedGvwrKg: 2470 },
  { make: 'Audi', model: 'A8', estimatedGvwrKg: 2710 },
  { make: 'Audi', model: 'Q2', estimatedGvwrKg: 1830 },
  { make: 'Audi', model: 'Q3', estimatedGvwrKg: 2070 },
  { make: 'Audi', model: 'Q3 Sportback', estimatedGvwrKg: 2070 },
  { make: 'Audi', model: 'Q4 e-tron', estimatedGvwrKg: 2720 },
  { make: 'Audi', model: 'Q5', estimatedGvwrKg: 2440 },
  { make: 'Audi', model: 'Q5 Sportback', estimatedGvwrKg: 2440 },
  { make: 'Audi', model: 'Q6 e-tron', estimatedGvwrKg: 2890 },
  { make: 'Audi', model: 'Q7', estimatedGvwrKg: 2980 },
  { make: 'Audi', model: 'Q8', estimatedGvwrKg: 3015 },
  { make: 'Audi', model: 'Q8 e-tron', estimatedGvwrKg: 3180 },
  { make: 'Audi', model: 'e-tron GT', estimatedGvwrKg: 2860 },
  { make: 'Audi', model: 'TT', estimatedGvwrKg: 1730 },
  { make: 'BMW', model: '1 Series', estimatedGvwrKg: 1870 },
  { make: 'BMW', model: '2 Series Coupe', estimatedGvwrKg: 1960 },
  { make: 'BMW', model: '2 Series Gran Coupe', estimatedGvwrKg: 1905 },
  { make: 'BMW', model: '2 Series Active Tourer', estimatedGvwrKg: 2045 },
  { make: 'BMW', model: '3 Series Sedan', estimatedGvwrKg: 2125 },
  { make: 'BMW', model: '3 Series Touring', estimatedGvwrKg: 2180 },
  { make: 'BMW', model: '4 Series Coupe', estimatedGvwrKg: 2075 },
  { make: 'BMW', model: '4 Series Gran Coupe', estimatedGvwrKg: 2175 },
  { make: 'BMW', model: '5 Series Sedan', estimatedGvwrKg: 2360 },
  { make: 'BMW', model: '5 Series Touring', estimatedGvwrKg: 2435 },
  { make: 'BMW', model: '7 Series', estimatedGvwrKg: 2710 },
  { make: 'BMW', model: '8 Series Gran Coupe', estimatedGvwrKg: 2410 },
  { make: 'BMW', model: 'X1', estimatedGvwrKg: 2075 },
  { make: 'BMW', model: 'X2', estimatedGvwrKg: 2095 },
  { make: 'BMW', model: 'X3', estimatedGvwrKg: 2420 },
  { make: 'BMW', model: 'X4', estimatedGvwrKg: 2440 },
  { make: 'BMW', model: 'X5', estimatedGvwrKg: 2860 },
  { make: 'BMW', model: 'X6', estimatedGvwrKg: 2865 },
  { make: 'BMW', model: 'X7', estimatedGvwrKg: 3220 },
  { make: 'BMW', model: 'XM', estimatedGvwrKg: 3300 },
  { make: 'BMW', model: 'i4', estimatedGvwrKg: 2605 },
  { make: 'BMW', model: 'i5', estimatedGvwrKg: 2740 },
  { make: 'BMW', model: 'i7', estimatedGvwrKg: 3250 },
  { make: 'BMW', model: 'iX1', estimatedGvwrKg: 2580 },
  { make: 'BMW', model: 'iX2', estimatedGvwrKg: 2600 },
  { make: 'BMW', model: 'iX3', estimatedGvwrKg: 2725 },
  { make: 'BMW', model: 'iX', estimatedGvwrKg: 3145 },
  { make: 'BMW', model: 'Z4', estimatedGvwrKg: 1740 },
  { make: 'Ford', model: 'Fiesta', estimatedGvwrKg: 1690 },
  { make: 'Ford', model: 'Focus', estimatedGvwrKg: 1850 },
  { make: 'Ford', model: 'Puma', estimatedGvwrKg: 1830 },
  { make: 'Ford', model: 'Kuga', estimatedGvwrKg: 2250 },
  { make: 'Ford', model: 'Mustang', estimatedGvwrKg: 2140 },
  { make: 'Ford', model: 'Mustang Mach-E', estimatedGvwrKg: 2690 },
  { make: 'Ford', model: 'Explorer EV', estimatedGvwrKg: 2675 },
  { make: 'Ford', model: 'Tourneo Custom', estimatedGvwrKg: 3200 },
  { make: 'Ford', model: 'Transit Custom', estimatedGvwrKg: 3225 },
  { make: 'Ford', model: 'Transit', estimatedGvwrKg: 3500 },
  { make: 'Ford', model: 'Ranger', estimatedGvwrKg: 3270 },
  { make: 'Mercedes-Benz', model: 'A-Class', estimatedGvwrKg: 1935 },
  { make: 'Mercedes-Benz', model: 'B-Class', estimatedGvwrKg: 1960 },
  { make: 'Mercedes-Benz', model: 'C-Class Saloon', estimatedGvwrKg: 2265 },
  { make: 'Mercedes-Benz', model: 'C-Class Estate', estimatedGvwrKg: 2320 },
  { make: 'Mercedes-Benz', model: 'E-Class Saloon', estimatedGvwrKg: 2450 },
  { make: 'Mercedes-Benz', model: 'E-Class Estate', estimatedGvwrKg: 2550 },
  { make: 'Mercedes-Benz', model: 'S-Class', estimatedGvwrKg: 2820 },
  { make: 'Mercedes-Benz', model: 'CLA Coupe', estimatedGvwrKg: 2025 },
  { make: 'Mercedes-Benz', model: 'CLE Coupe', estimatedGvwrKg: 2310 },
  { make: 'Mercedes-Benz', model: 'GLA', estimatedGvwrKg: 2070 },
  { make: 'Mercedes-Benz', model: 'GLB', estimatedGvwrKg: 2280 },
  { make: 'Mercedes-Benz', model: 'GLC SUV', estimatedGvwrKg: 2510 },
  { make: 'Mercedes-Benz', model: 'GLE SUV', estimatedGvwrKg: 3070 },
  { make: 'Mercedes-Benz', model: 'GLS', estimatedGvwrKg: 3250 },
  { make: 'Mercedes-Benz', model: 'G-Class', estimatedGvwrKg: 3200 },
  { make: 'Mercedes-Benz', model: 'EQA', estimatedGvwrKg: 2470 },
  { make: 'Mercedes-Benz', model: 'EQB', estimatedGvwrKg: 2580 },
  { make: 'Mercedes-Benz', model: 'EQE', estimatedGvwrKg: 2880 },
  { make: 'Mercedes-Benz', model: 'EQS', estimatedGvwrKg: 3225 },
  { make: 'Mercedes-Benz', model: 'Sprinter', estimatedGvwrKg: 3500 },
  { make: 'Mercedes-Benz', model: 'V-Class', estimatedGvwrKg: 3100 },
  { make: 'Mercedes-Benz', model: 'Vito', estimatedGvwrKg: 3050 },
  { make: 'Tesla', model: 'Model 3', estimatedGvwrKg: 2230 },
  { make: 'Tesla', model: 'Model Y', estimatedGvwrKg: 2405 },
  { make: 'Tesla', model: 'Model S', estimatedGvwrKg: 2530 },
  { make: 'Tesla', model: 'Model X', estimatedGvwrKg: 2970 },
  { make: 'Tesla', model: 'Cybertruck', estimatedGvwrKg: 3500 },
  { make: 'Toyota', model: 'Yaris', estimatedGvwrKg: 1615 },
  { make: 'Toyota', model: 'Yaris Cross', estimatedGvwrKg: 1690 },
  { make: 'Toyota', model: 'Corolla Hatchback', estimatedGvwrKg: 1820 },
  { make: 'Toyota', model: 'Corolla Touring Sports', estimatedGvwrKg: 1870 },
  { make: 'Toyota', model: 'Camry', estimatedGvwrKg: 2100 },
  { make: 'Toyota', model: 'C-HR', estimatedGvwrKg: 1930 },
  { make: 'Toyota', model: 'RAV4', estimatedGvwrKg: 2225 },
  { make: 'Toyota', model: 'Highlander', estimatedGvwrKg: 2720 },
  { make: 'Toyota', model: 'Land Cruiser', estimatedGvwrKg: 2990 },
  { make: 'Toyota', model: 'Hilux', estimatedGvwrKg: 3210 },
  { make: 'Toyota', model: 'Proace', estimatedGvwrKg: 3100 },
  { make: 'Volkswagen', model: 'Polo', estimatedGvwrKg: 1650 },
  { make: 'Volkswagen', model: 'Golf', estimatedGvwrKg: 1840 },
  { make: 'Volkswagen', model: 'Golf Variant', estimatedGvwrKg: 1920 },
  { make: 'Volkswagen', model: 'Passat Variant', estimatedGvwrKg: 2150 },
  { make: 'Volkswagen', model: 'Arteon', estimatedGvwrKg: 2170 },
  { make: 'Volkswagen', model: 'T-Cross', estimatedGvwrKg: 1740 },
  { make: 'Volkswagen', model: 'T-Roc', estimatedGvwrKg: 1860 },
  { make: 'Volkswagen', model: 'Tiguan', estimatedGvwrKg: 2260 },
  { make: 'Volkswagen', model: 'Touareg', estimatedGvwrKg: 2850 },
  { make: 'Volkswagen', model: 'ID.3', estimatedGvwrKg: 2270 },
  { make: 'Volkswagen', model: 'ID.4', estimatedGvwrKg: 2660 },
  { make: 'Volkswagen', model: 'ID.5', estimatedGvwrKg: 2660 },
  { make: 'Volkswagen', model: 'ID.7', estimatedGvwrKg: 2720 },
  { make: 'Volkswagen', model: 'ID. Buzz', estimatedGvwrKg: 3000 },
  { make: 'Volkswagen', model: 'Multivan', estimatedGvwrKg: 2850 },
  { make: 'Volkswagen', model: 'Transporter T6.1', estimatedGvwrKg: 3000 },
  { make: 'Volkswagen', model: 'Crafter', estimatedGvwrKg: 3500 }
];

export function sanitizeLicensePlate(input: string): string {
  return input.toUpperCase().replace(/[^A-Z0-9А-Я]/g, '');
}

export function validateLicensePlateFormat(plate: string): { valid: boolean; reason?: string } {
  const clean = sanitizeLicensePlate(plate);
  if (clean.length < 3) {
    return { valid: false, reason: 'License plate must contain at least 3 characters.' };
  }
  if (clean.length > 12) {
    return { valid: false, reason: 'License plate is too long (maximum 12 characters).' };
  }
  return { valid: true };
}