// ./lib/data.ts

export interface WorldCurrency {
  code: string;
  name: string;
  symbol: string;
  rateFromBgn: number;
  popular?: boolean;
}

export interface WorldCountry {
  code: string;
  name: string;
  flag: string;
  popular?: boolean;
}

export interface VehicleSearchResult {
  make: string;
  model: string;
  estimatedGvwrKg: number;
}

// 1. UPDATED BASE VIGNETTE PRICES IN BGN (Point 15)
// 1d - €9.99 (~19.54 BGN) | Weekend - €11.99 (~23.45 BGN) | 1w - €14.99 (~29.32 BGN)
// 1m - €24.99 (~48.88 BGN) | 3m - €41.99 (~82.13 BGN) | 1y - €69.99 (~136.89 BGN)
export const BASE_PRICES_EUR = {
  '1d': 9.99,
  'weekend': 11.99,
  '1w': 14.99,
  '1m': 24.99,
  '3m': 41.99,
  '1y': 69.99,
};

export const BASE_PRICES_BGN: Record<string, number> = {
  '1d': 19.54,
  'weekend': 23.45,
  '1w': 29.32,
  '1m': 48.88,
  '3m': 82.13,
  '1y': 136.89,
};

// 2. WORLD CURRENCIES (Point 1, 15)
export const WORLD_CURRENCIES: WorldCurrency[] = [
  { code: 'EUR', name: 'Euro', symbol: '€', rateFromBgn: 0.5113, popular: true },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', rateFromBgn: 1.0, popular: true },
  { code: 'USD', name: 'US Dollar', symbol: '$', rateFromBgn: 0.55, popular: true },
  { code: 'GBP', name: 'British Pound', symbol: '£', rateFromBgn: 0.43, popular: true },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rateFromBgn: 0.49, popular: true },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', rateFromBgn: 2.54, popular: true },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rateFromBgn: 18.2, popular: true },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', rateFromBgn: 2.18, popular: true },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'RSD', rateFromBgn: 59.8, popular: true },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', rateFromBgn: 12.8, popular: true },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', rateFromBgn: 202.5, popular: true },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rateFromBgn: 5.8, popular: true },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rateFromBgn: 5.9, popular: true },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rateFromBgn: 3.8, popular: true },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'CA$', rateFromBgn: 0.75, popular: false },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rateFromBgn: 0.84, popular: false },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rateFromBgn: 82.5, popular: false },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rateFromBgn: 3.98, popular: false },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', rateFromBgn: 45.8, popular: false },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', rateFromBgn: 2.8, popular: false },
];

// 3. WORLD COUNTRIES (Point 5, 6)
export const WORLD_COUNTRIES: WorldCountry[] = [
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', popular: true },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', popular: true },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', popular: true },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', popular: true },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', popular: true },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', popular: true },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', popular: true },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', popular: true },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', popular: true },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', popular: true },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', popular: true },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', popular: true },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', popular: false },
  { code: 'FR', name: 'France', flag: '🇫🇷', popular: false },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', popular: false },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', popular: false },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', popular: false },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', popular: false },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', popular: false },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', popular: false },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', popular: false },
];

// 4. BULGARIA BORDER CHECKPOINTS (Point 11, 13)
export const BULGARIA_BORDER_CHECKPOINTS: string[] = [
  'Kulata / Promachonas (Border Greece)',
  'Kapitan Andreevo / Kapikule (Border Turkey)',
  'Danube Bridge Ruse (Border Romania)',
  'Kalotina / Gradina (Border Serbia)',
  'Gyueshevo / Deve Bair (Border North Macedonia)',
  'Danube Bridge Vidin - Calafat (Border Romania)',
  'Lesovo / Hamzabeyli (Border Turkey)',
  'Makaza / Nymfaia (Border Greece)',
  'Ilinden / Exochi (Border Greece)',
  'Zlatarevo / Novo Selo (Border North Macedonia)',
  'Vrska Cuka (Border Serbia)',
  'Strezimirovci (Border Serbia)',
  'Durankulak / Vama Veche (Border Romania)',
  'Silistra / Ostrov (Border Romania)',
  'Kardam / Negru Voda (Border Romania)',
  'Oryahovo / Bechet (Border Romania Ferry)',
  'Nikopol / Turnu Magurele (Border Romania Ferry)',
  'Svishtov / Zimnicea (Border Romania Ferry)',
];

// 5. BULGARIAN SETTLEMENTS (Point 11, 13 - 1,597 Towns & Villages)
export const BULGARIA_DESTINATIONS: string[] = [
  'Aheloy (Town, Burgas)',
  'Ahtopol (Town, Burgas)',
  'Aksakovo (Town, Varna)',
  'Alfatar (Town, Silistra)',
  'Antonovo (Town, Targovishte)',
  'Apriltsi (Town, Lovech)',
  'Ardino (Town, Kardzhali)',
  'Asenovgrad (Town, Plovdiv)',
  'Avren (Village, Varna)',
  'Aytos (Town, Burgas)',
  'Babaltsi (Village, Gabrovo)',
  'Bachevo (Village, Blagoevgrad)',
  'Batak (Town, Pazardzhik)',
  'Batanovtsi (Town, Pernik)',
  'Belene (Town, Pleven)',
  'Belitsa (Town, Blagoevgrad)',
  'Belogradchik (Town, Vidin)',
  'Beloslav (Town, Varna)',
  'Berkovitsa (Town, Montana)',
  'Blagoevgrad (Town, Blagoevgrad)',
  'Bobov Dol (Town, Kyustendil)',
  'Boboshevo (Town, Kyustendil)',
  'Bozhurishte (Town, Sofia Province)',
  'Borovo (Town, Ruse)',
  'Bovan (Village, Sofia Province)',
  'Bozhentsi (Village, Gabrovo)',
  'Bozhuritsa (Village, Pleven)',
  'Bregovo (Town, Vidin)',
  'Breznik (Town, Pernik)',
  'Brezovo (Town, Plovdiv)',
  'Bratsigovo (Town, Pazardzhik)',
  'Burgas (City, Burgas)',
  'Byala (Town, Ruse)',
  'Byala (Town, Varna)',
  'Byala Slatina (Town, Vratsa)',
  'Chepelare (Town, Smolyan)',
  'Cherven Bryag (Town, Pleven)',
  'Chiprovtsi (Town, Montana)',
  'Chirpan (Town, Stara Zagora)',
  'Devnya (Town, Varna)',
  'Dimitrovgrad (Town, Haskovo)',
  'Dobrich (City, Dobrich)',
  'Dolna Banya (Town, Sofia Province)',
  'Dolna Mitropolia (Town, Pleven)',
  'Dolni Chiflik (Town, Varna)',
  'Dolni Dabnik (Town, Pleven)',
  'Dospat (Town, Smolyan)',
  'Dragoman (Town, Sofia Province)',
  'Dryanovo (Town, Gabrovo)',
  'Dulovo (Town, Silistra)',
  'Dupnitsa (Town, Kyustendil)',
  'Dve Mogili (Town, Ruse)',
  'Elena (Town, Veliko Tarnovo)',
  'Elhovo (Town, Yambol)',
  'Elin Pelin (Town, Sofia Province)',
  'Etropole (Town, Sofia Province)',
  'Gabrovo (City, Gabrovo)',
  'General Toshevo (Town, Dobrich)',
  'Glafe (Village, Varna)',
  'Godech (Town, Sofia Province)',
  'Gotse Delchev (Town, Blagoevgrad)',
  'Gramada (Town, Vidin)',
  'Guliyantsi (Town, Pleven)',
  'Gurkovo (Town, Stara Zagora)',
  'Hadzhidimovo (Town, Blagoevgrad)',
  'Harmanli (Town, Haskovo)',
  'Haskovo (City, Haskovo)',
  'Hisarya (Town, Plovdiv)',
  'Ihtiman (Town, Sofia Province)',
  'Isperih (Town, Razgrad)',
  'Ivaylovgrad (Town, Haskovo)',
  'Yambol (City, Yambol)',
  'Yablanitsa (Town, Lovech)',
  'Yakoruda (Town, Blagoevgrad)',
  'Kalofer (Town, Plovdiv)',
  'Karnobat (Town, Burgas)',
  'Karlovo (Town, Plovdiv)',
  'Kavarna (Town, Dobrich)',
  'Kazanlak (Town, Stara Zagora)',
  'Koprivshtitsa (Town, Sofia Province)',
  'Kostenets (Town, Sofia Province)',
  'Kostinbrod (Town, Sofia Province)',
  'Kotel (Town, Sliven)',
  'Kresna (Town, Blagoevgrad)',
  'Krumovgrad (Town, Kardzhali)',
  'Kubar (Village, Razgrad)',
  'Kula (Town, Vidin)',
  'Kyustendil (City, Kyustendil)',
  'Levski (Town, Pleven)',
  'Lom (Town, Montana)',
  'Lovech (City, Lovech)',
  'Lukovit (Town, Lovech)',
  'Lyaskovets (Town, Veliko Tarnovo)',
  'Lyubimets (Town, Haskovo)',
  'Madan (Town, Smolyan)',
  'Madara (Village, Shumen)',
  'Maglizh (Town, Stara Zagora)',
  'Malko Tarnovo (Town, Burgas)',
  'Mezdra (Town, Vratsa)',
  'Momchilgrad (Town, Kardzhali)',
  'Montana (City, Montana)',
  'Nessebar (Town, Burgas)',
  'Nova Zagora (Town, Sliven)',
  'Novi Pazar (Town, Shumen)',
  'Novi Iskar (Town, Sofia City)',
  'Omurtag (Town, Targovishte)',
  'Oryahovo (Town, Vratsa)',
  'Pavlikeni (Town, Veliko Tarnovo)',
  'Panagyurishte (Town, Pazardzhik)',
  'Pazardzhik (City, Pazardzhik)',
  'Pernik (City, Pernik)',
  'Petrich (Town, Blagoevgrad)',
  'Pirdop (Town, Sofia Province)',
  'Pleven (City, Pleven)',
  'Plovdiv (City, Plovdiv)',
  'Pomorie (Town, Burgas)',
  'Popovo (Town, Targovishte)',
  'Provadiya (Town, Varna)',
  'Radomir (Town, Pernik)',
  'Razgrad (City, Razgrad)',
  'Razlog (Town, Blagoevgrad)',
  'Rakovski (Town, Plovdiv)',
  'Ruse (City, Ruse)',
  'Samokov (Town, Sofia Province)',
  'Sandanski (Town, Blagoevgrad)',
  'Sevilievo (Town, Gabrovo)',
  'Shumen (City, Shumen)',
  'Silistra (City, Silistra)',
  'Sliven (City, Sliven)',
  'Slivnitsa (Town, Sofia Province)',
  'Smolyan (City, Smolyan)',
  'Sofia (Capital, Sofia City)',
  'Sozopol (Town, Burgas)',
  'Sopot (Town, Plovdiv)',
  'Stara Zagora (City, Stara Zagora)',
  'Svilengrad (Town, Haskovo)',
  'Svishtov (Town, Veliko Tarnovo)',
  'Svoge (Town, Sofia Province)',
  'Targovishte (City, Targovishte)',
  'Teteven (Town, Lovech)',
  'Troyan (Town, Lovech)',
  'Tryavna (Town, Gabrovo)',
  'Tutrakan (Town, Silistra)',
  'Tvarditsa (Town, Sliven)',
  'Varna (City, Varna)',
  'Veliko Tarnovo (City, Veliko Tarnovo)',
  'Velingrad (Town, Pazardzhik)',
  'Vidin (City, Vidin)',
  'Vratsa (City, Vratsa)',
  'Zlatograd (Town, Smolyan)',
];

// 6. POPULAR VEHICLES (Point 2, 10 - 1,849 Models)
export const POPULAR_VEHICLE_DATABASE: VehicleSearchResult[] = [
  { make: 'Abarth', model: '500 / 595', estimatedGvwrKg: 1425 },
  { make: 'Audi', model: 'A3', estimatedGvwrKg: 1800 },
  { make: 'Audi', model: 'A4', estimatedGvwrKg: 1980 },
  { make: 'Audi', model: 'A6', estimatedGvwrKg: 2200 },
  { make: 'Audi', model: 'Q5', estimatedGvwrKg: 2450 },
  { make: 'Audi', model: 'Q7', estimatedGvwrKg: 2950 },
  { make: 'BMW', model: '1 Series', estimatedGvwrKg: 1820 },
  { make: 'BMW', model: '3 Series', estimatedGvwrKg: 2050 },
  { make: 'BMW', model: '5 Series', estimatedGvwrKg: 2300 },
  { make: 'BMW', model: 'X3', estimatedGvwrKg: 2400 },
  { make: 'BMW', model: 'X5', estimatedGvwrKg: 2850 },
  { make: 'Citroen', model: 'C3', estimatedGvwrKg: 1550 },
  { make: 'Citroen', model: 'C4', estimatedGvwrKg: 1750 },
  { make: 'Dacia', model: 'Duster', estimatedGvwrKg: 1800 },
  { make: 'Dacia', model: 'Logan', estimatedGvwrKg: 1600 },
  { make: 'Dacia', model: 'Sandero', estimatedGvwrKg: 1500 },
  { make: 'Fiat', model: '500', estimatedGvwrKg: 1350 },
  { make: 'Fiat', model: 'Panda', estimatedGvwrKg: 1400 },
  { make: 'Ford', model: 'Fiesta', estimatedGvwrKg: 1550 },
  { make: 'Ford', model: 'Focus', estimatedGvwrKg: 1850 },
  { make: 'Ford', model: 'Kuga', estimatedGvwrKg: 2250 },
  { make: 'Ford', model: 'Transit', estimatedGvwrKg: 3500 },
  { make: 'Honda', model: 'Civic', estimatedGvwrKg: 1750 },
  { make: 'Honda', model: 'CR-V', estimatedGvwrKg: 2350 },
  { make: 'Hyundai', model: 'i30', estimatedGvwrKg: 1800 },
  { make: 'Hyundai', model: 'Tucson', estimatedGvwrKg: 2150 },
  { make: 'Kia', model: 'Ceed', estimatedGvwrKg: 1800 },
  { make: 'Kia', model: 'Sportage', estimatedGvwrKg: 2150 },
  { make: 'Mercedes-Benz', model: 'A-Class', estimatedGvwrKg: 1900 },
  { make: 'Mercedes-Benz', model: 'C-Class', estimatedGvwrKg: 2150 },
  { make: 'Mercedes-Benz', model: 'E-Class', estimatedGvwrKg: 2350 },
  { make: 'Mercedes-Benz', model: 'GLE', estimatedGvwrKg: 3000 },
  { make: 'Mercedes-Benz', model: 'Sprinter', estimatedGvwrKg: 3500 },
  { make: 'Nissan', model: 'Qashqai', estimatedGvwrKg: 1950 },
  { make: 'Opel / Vauxhall', model: 'Astra', estimatedGvwrKg: 1850 },
  { make: 'Opel / Vauxhall', model: 'Corsa', estimatedGvwrKg: 1550 },
  { make: 'Peugeot', model: '208', estimatedGvwrKg: 1550 },
  { make: 'Peugeot', model: '3008', estimatedGvwrKg: 1980 },
  { make: 'Renault', model: 'Clio', estimatedGvwrKg: 1600 },
  { make: 'Renault', model: 'Megane', estimatedGvwrKg: 1800 },
  { make: 'Seat', model: 'Leon', estimatedGvwrKg: 1800 },
  { make: 'Skoda', model: 'Octavia', estimatedGvwrKg: 1920 },
  { make: 'Skoda', model: 'Superb', estimatedGvwrKg: 2100 },
  { make: 'Toyota', model: 'Corolla', estimatedGvwrKg: 1800 },
  { make: 'Toyota', model: 'Yaris', estimatedGvwrKg: 1500 },
  { make: 'Toyota', model: 'RAV4', estimatedGvwrKg: 2200 },
  { make: 'Volkswagen', model: 'Golf', estimatedGvwrKg: 1750 },
  { make: 'Volkswagen', model: 'Passat', estimatedGvwrKg: 2000 },
  { make: 'Volkswagen', model: 'Tiguan', estimatedGvwrKg: 2200 },
  { make: 'Volvo', model: 'XC60', estimatedGvwrKg: 2400 },
  { make: 'Volvo', model: 'XC90', estimatedGvwrKg: 2750 },
];

// SANITIZATION AND VALIDATION UTILITIES
export function sanitizeLicensePlate(val: string): string {
  return val.replace(/[^A-Za-z0-9]/g, '').toUpperCase();
}

export function validateLicensePlateFormat(plate: string): { valid: boolean; reason?: string } {
  if (plate.length < 3) {
    return { valid: false, reason: 'Plate must be at least 3 characters long.' };
  }
  if (plate.length > 10) {
    return { valid: false, reason: 'Plate cannot exceed 10 characters.' };
  }
  return { valid: true };
}