// ./lib/data.ts

export interface VehicleDatabaseEntry {
  make: string;
  model: string;
  estimatedGvwrKg: number;
}

export interface CountryEntry {
  code: string;
  name: string;
  flag: string;
}

// Requirement 7: Top 10 popular countries first, remaining sorted alphabetically
export const WORLD_COUNTRIES: CountryEntry[] = [
  // Top 10 Popular
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  // Alphabetical Rest
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'AX', name: 'Åland Islands', flag: '🇦🇽' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿' },
  { code: 'AS', name: 'American Samoa', flag: '🇦🇸' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮' },
  { code: 'AQ', name: 'Antarctica', flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermuda', flag: '🇧🇲' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'CV', name: 'Cape Verde', flag: '🇨🇻' },
  { code: 'KY', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'CD', name: 'Congo (DRC)', flag: '🇨🇩' },
  { code: 'CK', name: 'Cook Islands', flag: '🇨🇰' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷' },
  { code: 'GL', name: 'Greenland', flag: '🇬🇱' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'XK', name: 'Kosovo', flag: '🇽🇰' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MO', name: 'Macau', flag: '🇲🇴' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'PR', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VA', name: 'Vatican City', flag: '🇻🇦' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼' }
];

// Requirement 2: Comprehensive list of vehicle makes & models
export const POPULAR_VEHICLE_DATABASE: VehicleDatabaseEntry[] = [
  { make: 'Abarth', model: '500', estimatedGvwrKg: 1425 },
  { make: 'Abarth', model: '500e', estimatedGvwrKg: 1815 },
  { make: 'Abarth', model: '595', estimatedGvwrKg: 1430 },
  { make: 'Abarth', model: '600e', estimatedGvwrKg: 1980 },
  { make: 'Abarth', model: '695', estimatedGvwrKg: 1440 },
  { make: 'Abarth', model: '124 Spider', estimatedGvwrKg: 1315 },
  { make: 'Abarth', model: 'Grande Punto', estimatedGvwrKg: 1665 },
  { make: 'Abarth', model: 'Punto Evo', estimatedGvwrKg: 1685 },
  { make: 'Acura', model: 'ADX', estimatedGvwrKg: 2150 },
  { make: 'Acura', model: 'CDX', estimatedGvwrKg: 1990 },
  { make: 'Acura', model: 'CL', estimatedGvwrKg: 2010 },
  { make: 'Acura', model: 'CSX', estimatedGvwrKg: 1750 },
  { make: 'Acura', model: 'EL', estimatedGvwrKg: 1660 },
  { make: 'Acura', model: 'ILX', estimatedGvwrKg: 1840 },
  { make: 'Acura', model: 'Integra', estimatedGvwrKg: 1880 },
  { make: 'Acura', model: 'Legend', estimatedGvwrKg: 2110 },
  { make: 'Acura', model: 'MDX', estimatedGvwrKg: 2620 },
  { make: 'Acura', model: 'NSX', estimatedGvwrKg: 1810 },
  { make: 'Acura', model: 'RDX', estimatedGvwrKg: 2280 },
  { make: 'Alfa Romeo', model: '147', estimatedGvwrKg: 1730 },
  { make: 'Alfa Romeo', model: '156', estimatedGvwrKg: 1820 },
  { make: 'Alfa Romeo', model: '159', estimatedGvwrKg: 2060 },
  { make: 'Alfa Romeo', model: 'Giulia', estimatedGvwrKg: 2050 },
  { make: 'Alfa Romeo', model: 'Giulietta', estimatedGvwrKg: 1805 },
  { make: 'Alfa Romeo', model: 'Junior', estimatedGvwrKg: 1980 },
  { make: 'Alfa Romeo', model: 'Mito', estimatedGvwrKg: 1665 },
  { make: 'Alfa Romeo', model: 'Stelvio', estimatedGvwrKg: 2300 },
  { make: 'Alfa Romeo', model: 'Tonale', estimatedGvwrKg: 2135 },
  { make: 'Audi', model: 'A1', estimatedGvwrKg: 1680 },
  { make: 'Audi', model: 'A3', estimatedGvwrKg: 1870 },
  { make: 'Audi', model: 'A4', estimatedGvwrKg: 2095 },
  { make: 'Audi', model: 'A5', estimatedGvwrKg: 2140 },
  { make: 'Audi', model: 'A6', estimatedGvwrKg: 2325 },
  { make: 'Audi', model: 'A7', estimatedGvwrKg: 2470 },
  { make: 'Audi', model: 'A8', estimatedGvwrKg: 2700 },
  { make: 'Audi', model: 'Q2', estimatedGvwrKg: 1860 },
  { make: 'Audi', model: 'Q3', estimatedGvwrKg: 2140 },
  { make: 'Audi', model: 'Q5', estimatedGvwrKg: 2495 },
  { make: 'Audi', model: 'Q7', estimatedGvwrKg: 2950 },
  { make: 'Audi', model: 'Q8', estimatedGvwrKg: 3030 },
  { make: 'BMW', model: '1 Series', estimatedGvwrKg: 1870 },
  { make: 'BMW', model: '2 Series', estimatedGvwrKg: 1960 },
  { make: 'BMW', model: '3 Series', estimatedGvwrKg: 2135 },
  { make: 'BMW', model: '4 Series', estimatedGvwrKg: 2170 },
  { make: 'BMW', model: '5 Series', estimatedGvwrKg: 2360 },
  { make: 'BMW', model: '7 Series', estimatedGvwrKg: 2790 },
  { make: 'BMW', model: 'X1', estimatedGvwrKg: 2140 },
  { make: 'BMW', model: 'X3', estimatedGvwrKg: 2420 },
  { make: 'BMW', model: 'X5', estimatedGvwrKg: 2860 },
  { make: 'BMW', model: 'X7', estimatedGvwrKg: 3290 },
  { make: 'Citroën', model: 'C3', estimatedGvwrKg: 1570 },
  { make: 'Citroën', model: 'C4', estimatedGvwrKg: 1790 },
  { make: 'Citroën', model: 'C5 Aircross', estimatedGvwrKg: 2110 },
  { make: 'Dacia', model: 'Duster', estimatedGvwrKg: 1760 },
  { make: 'Dacia', model: 'Logan', estimatedGvwrKg: 1540 },
  { make: 'Dacia', model: 'Sandero', estimatedGvwrKg: 1530 },
  { make: 'Dacia', model: 'Spring', estimatedGvwrKg: 1300 },
  { make: 'Fiat', model: '500', estimatedGvwrKg: 1345 },
  { make: 'Fiat', model: 'Panda', estimatedGvwrKg: 1420 },
  { make: 'Fiat', model: 'Tipo', estimatedGvwrKg: 1740 },
  { make: 'Ford', model: 'Fiesta', estimatedGvwrKg: 1680 },
  { make: 'Ford', model: 'Focus', estimatedGvwrKg: 1905 },
  { make: 'Ford', model: 'Kuga', estimatedGvwrKg: 2250 },
  { make: 'Ford', model: 'Mondeo', estimatedGvwrKg: 2160 },

  { make: 'Mercedes-Benz', model: 'A-Class', estimatedGvwrKg: 1935 },
  { make: 'Mercedes-Benz', model: 'C-Class', estimatedGvwrKg: 2265 },
  { make: 'Mercedes-Benz', model: 'E-Class', estimatedGvwrKg: 2450 },
  { make: 'Mercedes-Benz', model: 'GLC', estimatedGvwrKg: 2510 },
  { make: 'Mercedes-Benz', model: 'GLE', estimatedGvwrKg: 3000 },
  { make: 'Opel', model: 'Astra', estimatedGvwrKg: 1840 },
  { make: 'Opel', model: 'Corsa', estimatedGvwrKg: 1620 },
  { make: 'Opel', model: 'Insignia', estimatedGvwrKg: 2140 },
  { make: 'Peugeot', model: '208', estimatedGvwrKg: 1590 },
  { make: 'Peugeot', model: '308', estimatedGvwrKg: 1870 },
  { make: 'Peugeot', model: '3008', estimatedGvwrKg: 1980 },
  { make: 'Renault', model: 'Clio', estimatedGvwrKg: 1600 },
  { make: 'Renault', model: 'Megane', estimatedGvwrKg: 1820 },
  { make: 'Skoda', model: 'Fabia', estimatedGvwrKg: 1580 },
  { make: 'Skoda', model: 'Octavia', estimatedGvwrKg: 1920 },
  { make: 'Skoda', model: 'Superb', estimatedGvwrKg: 2170 },
  { make: 'Toyota', model: 'Corolla', estimatedGvwrKg: 1835 },
  { make: 'Toyota', model: 'RAV4', estimatedGvwrKg: 2225 },
  { make: 'Toyota', model: 'Yaris', estimatedGvwrKg: 1560 },
  { make: 'Volkswagen', model: 'Golf', estimatedGvwrKg: 1840 },
  { make: 'Volkswagen', model: 'Passat', estimatedGvwrKg: 2060 },
  { make: 'Volkswagen', model: 'Polo', estimatedGvwrKg: 1630 },
  { make: 'Volkswagen', model: 'Tiguan', estimatedGvwrKg: 2130 }
];

export function sanitizeLicensePlate(input: string): string {
  if (!input) return '';
  return input
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .trim();
}

export function validateLicensePlateFormat(plate: string): { valid: boolean; reason?: string } {
  if (!plate || plate.length < 2) {
    return { valid: false, reason: 'License plate must be at least 2 characters long.' };
  }
  if (plate.length > 10) {
    return { valid: false, reason: 'License plate must not exceed 10 characters.' };
  }
  return { valid: true };
}